name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command to test print
      - name: test print
        run: printf "print hi\nexit\n" | python3 lang.py -c
      - name: test shell
        run: printf "shell echo test shell\nexit\n" | python3 lang.py -c
      - name: test var
        run: printf "hi:=wow\nprint hi$\nexit\n" | python3 lang.py -c
      - name: test cd
        run: printf "shell mkdir test shell\ncd test\npwd\ncd ..\nexit\n" | python3 lang.py -c
      - name: test ls
        run: printf "ls\nexit\n" | python3 lang.py -c
      - name: test calc
        run: printf "expr:=1 + 2\ncalc expr$\nexit\n" | python3 lang.py -c
      - name: test pwd
        run: printf "pwd\nexit\n" | python3 lang.py -c
